# Generated by Django 6.0.6 on 2026-06-22 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push'), ('email', 'Email')], max_length=10)),
                ('notif_type', models.CharField(choices=[('funds_secured', 'Fonds sécurisés'), ('delivery_confirmed', 'Livraison confirmée'), ('dispute_opened', 'Litige ouvert'), ('dispute_resolved', 'Litige résolu'), ('payment_released', 'Paiement libéré'), ('otp_code', 'Code OTP'), ('account_frozen', 'Compte gelé')], max_length=25)),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Remis'), ('failed', 'Échoué')], default='queued', max_length=10)),
                ('message', models.TextField()),
                ('external_id', models.CharField(blank=True, help_text='ID Twilio ou opérateur SMS', max_length=100, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transactions.transaction')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
