# Generated by Django 6.0.6 on 2026-06-22 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('non_delivery', 'Non livraison'), ('non_conformity', 'Produit non conforme'), ('fraud', 'Fraude'), ('other', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('under_review', 'En cours d examen'), ('resolved', 'Résolu'), ('escalated', 'Escaladé')], default='open', max_length=15)),
                ('description', models.TextField()),
                ('decision', models.CharField(blank=True, choices=[('refund_buyer', 'Remboursement acheteur'), ('release_seller', 'Paiement vendeur'), ('partial', 'Partiel'), ('void', 'Annulé sans suite')], max_length=20, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='decided_disputes', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='transactions.transaction')),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('screenshot', 'Capture ecran'), ('delivery_slip', 'Bordereau de livraison'), ('other', 'Autre')], max_length=20)),
                ('storage_url', models.TextField()),
                ('hash_sha256', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='disputes.dispute')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidences',
                'ordering': ['-created_at'],
            },
        ),
    ]
