# Generated by Django 6.0.6 on 2026-06-22 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_slug', models.SlugField(max_length=80, unique=True)),
                ('shop_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_pro', models.BooleanField(default=False)),
                ('pro_expires_at', models.DateTimeField(blank=True, null=True)),
                ('total_secured_gmv', models.BigIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('green', 'Vert Certifié'), ('grey', 'Gris Inconnu'), ('orange', 'Orange Suspect'), ('red', 'Rouge Bloqué')], default='grey', max_length=10)),
                ('score_value', models.SmallIntegerField(default=50)),
                ('total_transactions', models.IntegerField(default=0)),
                ('dispute_rate_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('last_fraud_flag_at', models.DateTimeField(blank=True, null=True)),
                ('recalculated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to='vendors.vendor')),
            ],
            options={
                'db_table': 'trust_scores',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Vendeur Pro')], default='pro', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('payment_ref', models.CharField(max_length=100)),
                ('amount_fcfa', models.IntegerField(default=5000)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='vendors.vendor')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-started_at'],
            },
        ),
    ]
