# Generated by Django 6.0.6 on 2026-06-22 19:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('payment_pending', 'Paiement en attente'), ('funds_secured', 'Fonds sécurisés'), ('delivery_in_progress', 'Livraison en cours'), ('completed', 'Complété'), ('disputed', 'En litige'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='initiated', max_length=25)),
                ('amount_fcfa', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fee_fcfa', models.IntegerField(default=200)),
                ('product_description', models.TextField()),
                ('delivery_zone', models.CharField(max_length=200)),
                ('delivery_deadline', models.DateTimeField()),
                ('psp_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payout_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='vendors.vendor')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
